### ISSUE TITLE
qt.qpa.xcb: could not connect to display

### ISSUE THREAD

**Issue by Critter** [MikeBeas/switchblade-ui#2]
well. surprise surprise. it's me again.

I've been writing apps for about 30 years, haven't felt more like a newb than today. smh.

I run `npm install` it loads a bunch of shit, but then throws at this:

```
error code E401
782 error 401 Unauthorized - GET https://npm.pkg.github.com/download/@mikebeas/switchblade-sdk/1.0.0/d32e9b79d56b3219f267f8d94eb55de1a505e7>
783 verbose exit 1
784 timing npm Completed in 5923ms
785 verbose unfinished npm timer reify 1686167603243
786 verbose unfinished npm timer reify:unpack 1686167603546
787 verbose unfinished npm timer reifyNode:node_modules/@mikebeas/switchblade-sdk 1686167603564
788 verbose code 1
```

To be honest, I don't even know if I'm running the right fucking commands. 🤷🏻‍♂️ 

When I run `npm start` It looks like it wants to, then bam!

> switchblade-ui@1.0.0 start
> vite

```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted (core dumped)
```

any ideas, mate?

**Comment by MikeBeas** [comment]
the npm issue is entirely my fault, i forgot to set the package to public when i published the repo. sorry about that! give it a go now!

**Comment by Critter** [comment]
are those the right commands to be running?  I still get the same 2 errors.

**Comment by MikeBeas** [comment]
I'm seeing the npm issue on my end as well now. I'll see what's going on.

**Comment by MikeBeas** [comment]
OK I think I see the issue installing the package. It looks like Github requires you to be authenticated even to install public packages, which is really stupid. I'll see what I can do to get around it.

**Comment by Critter** [comment]
ah.k.

will that sort that error on start then too?

**Comment by MikeBeas** [comment]
Not sure. I would imagine having missing depdencies is probably not great for the startup process, but based on a little googling that error might be related to the actual machine running the software in this case.

**Comment by MikeBeas** [comment]
OK, I just pushed switchblade-ui v1.0.1 which should fix the npm install issue. The switchblade-sdk package is now available from npm instead of GitHub Packages: https://www.npmjs.com/package/switchblade-sdk

Can you give the new version a try and see if it fixes that issue? Hopefully it'll fix both but I'm not so sure about the second one since it looks like an operating system thing.

**Comment by MikeBeas** [comment]
Whoops I made a big mistake while publishing 1.0.1 but I've just re-published it with the errors fixed. Give _that_ a try now.

**Comment by Critter** [comment]
did a `git fetch --all`

`npm install`

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://npm.pkg.github.com/download/@mikebeas/switchblade-sdk/1.0.0/d32e9b79d56b3219f267f8d94eb55de1a505e748 - npm package "switchblade-sdk" does not exist under owner "mikebeas"
npm ERR! 404 
npm ERR! 404  '@mikebeas/switchblade-sdk@https://npm.pkg.github.com/download/@mikebeas/switchblade-sdk/1.0.0/d32e9b79d56b3219f267f8d94eb55de1a505e748' is not in this registry.
```

**Comment by MikeBeas** [comment]
Did you do a git pull or just a git fetch? What commit are you on right now?

**Comment by Critter** [comment]
got it. just did a pull and got the latest. `npm install`  completed with 0 errors. off to try the startup :/

**Comment by Critter** [comment]
```
VITE v4.3.9  ready in 546 ms

  ➜  Local:   http://localhost:8500/
  ➜  Network: use --host to expose
  ➜  press h to show help
```

looks promising!

**Comment by Critter** [comment]
Fuck Yeah!!!
![image](https://github.com/MikeBeas/switchblade-ui/assets/73031/595c4faf-94a0-4c40-93ac-80099897c53c)

dude... thanks for all the help!

**Comment by MikeBeas** [comment]
no problem! enjoy!
